export const folders = [
  { id: 'travel', name: '旅行攻略', color: '#f4d48a' },
  { id: 'game', name: '游戏地图', color: '#a9c8de' },
  { id: 'study', name: '学习资料', color: '#b9ddbf' },
  { id: 'contest', name: '竞赛材料', color: '#e3c18c' },
  { id: 'cooking', name: '生活菜谱', color: '#ead0a7' },
  { id: 'notes', name: '杂项笔记', color: '#dbc7e6' },
];

export const seedAssets = [
  {
    id: 'asset-xian-food',
    type: 'image',
    variant: 'tall',
    folderId: 'travel',
    source: '小红书截图',
    title: '西安两日美食路线',
    summary: '回民街、钟楼夜景、陕西历史博物馆和大雁塔串成两天路线，重点是提前预约博物馆。',
    content: '西安两日美食攻略：第一天回民街、钟楼夜景；第二天陕西历史博物馆、大雁塔。建议提前预约博物馆，准备身份证。',
    tags: ['西安', '美食攻略', '博物馆预约', '旅行'],
    semantic: ['旅游', '攻略', '路线', '预约', '身份证', '红烧肉做法'],
    confidence: 86,
    color: 'linear-gradient(180deg, #f6dfa3, #f2c86d)',
    createdAt: '2026-05-07T08:00:00.000Z',
  },
  {
    id: 'asset-genshin-map',
    type: 'image',
    variant: 'wide',
    folderId: 'game',
    source: '游戏攻略截图',
    title: '风龙废墟路线图',
    summary: '地图标记了传送点、风场入口和高处平台路线，适合下次游戏时快速寻回。',
    content: '游戏地图：风龙废墟入口，从七天神像向西北移动，沿断桥进入风场。',
    tags: ['原神', '风龙废墟', '游戏地图'],
    semantic: ['怎么去风龙废墟', '路线', '地图', '传送点', '游戏攻略'],
    confidence: 91,
    color: 'linear-gradient(180deg, #bfd7ea, #9ec4dd)',
    createdAt: '2026-05-07T08:03:00.000Z',
  },
  {
    id: 'asset-cet6-note',
    type: 'text',
    variant: 'text',
    folderId: 'study',
    source: '语音速记转文字',
    title: '英语六级作文模板',
    summary: '观点类作文先让步再转折，结尾给具体建议，适合考前背诵。',
    content: '作文模板：Although some people believe..., I still argue that... The reason is not only..., but also...',
    tags: ['英语六级', '作文模板', '学习'],
    semantic: ['考试资料', '英语', '作文', '模板', '复习'],
    confidence: 83,
    color: 'linear-gradient(180deg, #cce4cd, #a6d4a9)',
    createdAt: '2026-05-07T08:06:00.000Z',
  },
  {
    id: 'asset-aigc-contest',
    type: 'image',
    variant: 'tall',
    folderId: 'contest',
    source: '班级群截图',
    title: 'AIGC 创新赛报名材料',
    summary: '报名截止为 2026-05-11 08:00，需要策划文档、团队介绍、原型图和指导教师信息。',
    content: 'AIGC创新赛应用赛道报名截止：2026年5月11日08:00。请提交作品策划文档、团队介绍、原型图和指导教师信息。',
    tags: ['AIGC竞赛', '报名材料', '截止时间'],
    semantic: ['比赛', '报名', '材料清单', '截止', '作品策划'],
    confidence: 94,
    color: 'linear-gradient(180deg, #f2d7a3, #e8b879)',
    tasks: ['完成作品策划文档', '整理团队介绍与成员分工', '补齐 5-8 张原型界面图', '提交前确认指导教师信息'],
    materials: ['策划文档', '团队介绍', '原型图', '指导教师信息'],
    reminders: ['2026-05-10 20:00 检查材料', '2026-05-11 07:30 提交提醒'],
    createdAt: '2026-05-07T08:09:00.000Z',
  },
  {
    id: 'asset-pork-recipe',
    type: 'image',
    variant: 'normal',
    folderId: 'cooking',
    source: '短视频截图',
    title: '红烧肉做法要点',
    summary: '先煸出油脂，再炒糖色，加入热水小火焖 45 分钟，最后大火收汁。',
    content: '红烧肉：五花肉焯水，冰糖炒糖色，生抽老抽调味，热水没过肉，小火炖煮。',
    tags: ['红烧肉', '菜谱', '生活'],
    semantic: ['红烧肉做法', '菜谱', '做饭', '五花肉'],
    confidence: 88,
    color: 'linear-gradient(180deg, #efdbc1, #e8c58e)',
    createdAt: '2026-05-07T08:12:00.000Z',
  },
  {
    id: 'asset-python-code',
    type: 'image',
    variant: 'wide',
    folderId: 'study',
    source: '网页长截图',
    title: 'Python 文件读取片段',
    summary: 'AI 已从截图中提取代码片段，可在详情页复制复用。',
    content: "with open('data.txt', 'r', encoding='utf-8') as f:\n    lines = f.readlines()",
    tags: ['Python', '代码片段', '学习'],
    semantic: ['代码', '教程', '复制', 'Python', '文件读取'],
    confidence: 89,
    color: 'linear-gradient(180deg, #d7ead9, #b9d8bc)',
    createdAt: '2026-05-07T08:15:00.000Z',
  },
];

export const captureSamples = [
  {
    label: '导入旅游攻略截图',
    source: '网页截图',
    payload: {
      type: 'image',
      variant: 'tall',
      folderId: 'travel',
      title: '长沙三天夜宵清单',
      summary: '坡子街、黄兴路、文和友和茶颜悦色串成一条夜游路线。',
      content: '长沙夜宵攻略：坡子街臭豆腐、黄兴路步行街、超级文和友。建议避开周末晚高峰。',
      tags: ['长沙', '夜宵', '旅行'],
      semantic: ['长沙攻略', '旅游', '美食', '夜宵'],
      color: 'linear-gradient(180deg, #f7ddb0, #f0c87a)',
    },
  },
  {
    label: '添加纯文本速记',
    source: '手动速记',
    payload: {
      type: 'text',
      variant: 'text',
      folderId: 'notes',
      title: '答辩开场话术',
      summary: '先讲痛点，再讲端侧隐私优势，最后演示搜索状态保活。',
      content: '答辩顺序：痛点 - 沙盒 - 悬浮捕获 - AI 打标 - 金库 - 语义搜索 - 状态保活。',
      tags: ['答辩', '演示脚本', '项目'],
      semantic: ['答辩', '计划', '项目介绍', '演示'],
      color: 'linear-gradient(180deg, #e8dbf0, #d7c2e4)',
    },
  },
  {
    label: '模拟 AI 失败保存',
    source: '离线捕获',
    payload: {
      type: 'image',
      variant: 'normal',
      folderId: 'notes',
      title: '待重新识别截图',
      summary: '网络或模型暂不可用，图片已先进入应用沙盒，稍后可重新识别。',
      content: '离线状态下捕获的截图，等待端侧模型重新处理。',
      tags: ['待识别', '离线保存'],
      semantic: ['失败', '离线', '重新识别'],
      confidence: 22,
      status: 'pending',
      color: 'linear-gradient(180deg, #e6d7d2, #d7beb3)',
    },
  },
];
